### ISSUE TITLE
Does not work with webpack, react-native

### ISSUE THREAD

**Issue by zurawiki** [nieldlr/Hanzi#31]
## See #36 for the relevant PR

This module works great with in server-side and browserify (haven't tested it myself though) but I want to use this module in my webpack based project and in my react-native project. 

Right now this module use of the core node library `require('fs')` is incompatible with these environments without additional configuration, like btfs. I want to replace usage of `fs` by requiring the text modules directly if possible. 

I'd like to make this change in two steps. 

1. Move all the code that reads the text files to a new file

2. Use `require()` to read those data files. A downside here is that we need to wrap the files with some ES6 javascript to load the string properly. This is easy enough to accomplish with a node script I wrote or shell one-liner. 

I'm happy to rebase this commit <https://github.com/zurawiki/Hanzi/commit/af3af629356ee2cb3ab9ca01fc08caea0917dc69> if you would accept a pull request.

**Comment by zurawiki** [comment]
In my nextgen branch <https://github.com/zurawiki/Hanzi/tree/nextgen> I made a number of structural changes including
  - consolidating all the data files into one directory
  - consolidating and organizing test code
  - adding tooling for the non module that allows developer to write more modern, succinct ES6+ JavaScript
  - integrate linting and other common code formatting tools to the repo
  - setting up continuous integration testing over a variety of node.js version (with browser environments planned)

Let me know if you would want to merge any of these changes and I'm happy to send the pull requests your way!

**Comment by nieldlr** [comment]
Woah @zurawiki!

Amazing ideas here! Hanzi definitely needs some updating to catch up with modern JS. Let me look through your code and think through a few things here and I'll get back to you soon.

**Comment by nieldlr** [comment]
Heya @zurawiki,

so sorry for my delay. Would like to keep the momentum here.

I wonder, if we could break these into different PRs. The ones I'm most excited about & thinking about how to split this up:

1) Moving to requiring files instead of using `fs`.
2) Updating things to ES6.
3) Linting + improved testing environment + continuous integration
4) Script to update the CC-CEDICT data
5) Consolidating all data files

I wonder if it's possible to create separate PRs for those? I might be a tricky I imagine. What do you think? I'm happy to take in any combination here to make pulling your amazing work easier for you. For example, consolidating the data files might be easy to add another PR.

Again, thanks for all these amazing improvements! Excited for this.

**Comment by Dans-io** [comment]
Any updates on this @nieldlr?
Thanks!

**Comment by nieldlr** [comment]
Heya @Dans-io, this should be on master at the moment (merged here: https://github.com/nieldlr/Hanzi/pull/36). I haven't quite fully run the tests for these in webpack/react-native setups. Feel free to give it a try. 👍 It should be all smooth.

I still to publish these updates to npm if that might what you're looking for?

**Comment by Dans-io** [comment]
Oh got it. Yes I was asking because it got it from NPM earlier today and the issue was still there. Thank you so much for building this, it's really great.

**Comment by nieldlr** [comment]
@Dans-io awesome. I'll see if I can publish a new version sometime today.

Thanks for the kind words!

**Comment by nieldlr** [comment]
Heya @Dans-io, it should now be published under v2.0.0. Have fun! Let me know if there's anything else you need.
